spring.application.name=frontdesk.backend
spring.datasource.url=jdbc:mysql://localhost:3306/frontdesk?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.security.user.name=admin
spring.security.user.password=admin
spring.application.version=1.0.0
server.port=8080

# JWT configuration (HS256)
app.jwt.secretkey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y
app.jwt.expiration-ms=86400000
